Reordered JSON attributes in SimulateCommand
ppy/osu-tools pull request #125
Opened 2021-10-12 19:23 UTC by matthieu-locussol

This fixes issue #124 

It changes the behavior of the simulate command when outputing json using `--json` flag.

Command:
```bash
dotnet run --project PerformanceCalculator.csproj --configuration Release -- simulate osu map.osu -m:Hd -m:HR -G:5 --json
```

Before:
```json
{
  "Beatmap": "xi - FREEDOM DiVE (Nakagawa-Kanon) [FOUR DIMENSIONS]",
  "Accuracy": 222.7765006385657,
  "Combo": 2385.0,
  "Great": 1978.0,
  "Ok": 5.0,
  "Meh": 0.0,
  "Miss": 0.0,
  "Mods": "HD, HR",
  "Aim": 282.549316567955,
  "Speed": 382.89578323239095,
  "Flashlight": 0.0,
  "OD": 10.0,
  "AR": 10.0,
  "Max Combo": 2385.0,
  "pp": 902.472286786258
}
```

After:

```json
{
  "Beatmap": "xi - FREEDOM DiVE (Nakagawa-Kanon) [FOUR DIMENSIONS]",
  "ScoreStatistics": {
    "Accuracy": 99.83190452176837,
    "Combo": 2385.0,
    "Great": 1978.0,
    "Ok": 5.0,
    "Meh": 0.0,
    "Miss": 0.0
  },
  "Aim": 282.549316567955,
  "Speed": 382.89578323239095,
  "Accuracy": 222.7765006385657,
  "Flashlight": 0.0,
  "OD": 10.0,
  "AR": 10.0,
  "Max Combo": 2385.0,
  "Mods": "HD, HR",
  "pp": 902.472286786258
}
```

2021-10-12 19:48 UTC, matthieu-locussol commented
That's right, sorry about that.

I grouped the play values together under a `pp` item as proposed above.

2021-10-13 07:04 UTC, matthieu-locussol commented
I updated the PR to add score stats in `ScoreStatistics` and let `pp` outside.

2021-10-13 08:22 UTC, smoogipoo requested changes
Also please don't PR from master in the future.

2021-10-13 08:22 UTC, smoogipoo commented on PerformanceCalculator/Simulate/SimulateCommand.cs
> +                o["ScoreStatistics"] = new JObject();
Rename to `Statistics`, it's more common.

2021-10-13 08:26 UTC, smoogipoo approved these changes

2021-10-13 08:29 UTC, merged