Move HitObject Panel Information to a Side Bar in the Object Inspector
ppy/osu-tools pull request #172
Opened 2023-01-10 23:11 UTC by srb2thepast

This change simply moves the information contained in each respective mode's panel to a side bar for easier reference.
Fast forwarding or rewinding the timeline with Q and E is added in as well. Holding Shift slows it down more and holding Ctrl speeds it up.)

Video Preview:

https://user-images.githubusercontent.com/19241426/211680765-e4eccaf2-6254-4c38-9b0c-937fef31c59a.mp4

2023-01-22 11:20 UTC, stanriders commented
I like the concept, but I think the implementation can be simplified. From a quick glance I can see a looot of code quality issues already though, please run code formatting before committing next time

2023-01-22 11:39 UTC, stanriders requested changes
I think the whole logic can be simplified into:

- `ObjectInspector` creates `DebugValueList`
- `DebugValueList` has a `Bindable<DifficultyHitObject>` which is bind to the current object on screen by the `ObjectInspector`

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +    public partial class DebugValueList : Container
I think it'd be better to call this something like `ObjectDifficultyValuesContainer`, since it's not a list nor its for debugging

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/CatchObjectInspectorRuleset.cs
> +            valueList.UpdateValues();
This seems to be exactly what the `Bindable`s are for

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                    flowContainer.AddText($"   {ValuePair.Key}:\n", t =>
Use `Margin` instead of manually padding using whitespaces

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                        Y = 3500,
This repeats what's in the `Size` already. Also, you can just use `AutoSizeAxes = Axes.Y`

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                    Height = 670,
Why is the height here a const?

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +                Padding = new MarginPadding() { Left = side_bar_width, Right = 0 },
`Right = 0` can be removed

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +            AddInternal(inspectContainer = new Container
`AddRange(new[] { all three containers })`

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +                                new Box { Colour = Colour4.Gray, RelativeSizeAxes = Axes.Both, Y = 2},
What's going on here?

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/OsuObjectInspectorRuleset.cs
> +        public const int HIT_OBJECT_FADE_OUT_EXTENSION = 0;
Just remove it

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/OsuObjectInspectorRuleset.cs
> +                    drawHitList.Last().Colour = Colour4.Red;
I don't think this is necessary

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                    t.Colour = Colour4.Pink;
It's not like the tools try to be stylish or anything, but I think this looks kinda ugly

2023-01-22 11:39 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                    t.Scale = new Vector2(1.8f);
Why not just set font size instead?

2023-01-26 21:29 UTC, srb2thepast commented
> I like the concept, but I think the implementation can be simplified. From a quick glance I can see a looot of code quality issues already though, please run code formatting before committing next time

alright. is running code formatting just done via `dotnet format`?

2023-01-26 23:04 UTC, srb2thepast commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                    Height = 670,
It was originally due to an issue with sizing, but using more of `AutoSizeAxes` has fixed it. I'm now replacing the two with `AutoSizeAxes = Axes.Both`.

2023-01-26 23:17 UTC, srb2thepast commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                    t.Colour = Colour4.Pink;
Would it be fine if the color was removed?

2023-01-26 23:29 UTC, srb2thepast commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                    t.Scale = new Vector2(1.8f);
I missed this, using font size would be better.

2023-01-26 23:39 UTC, srb2thepast commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +                                new Box { Colour = Colour4.Gray, RelativeSizeAxes = Axes.Both, Y = 2},
I tried adding a shadow on the bar for the Catch Ruleset for a better look. It resulted in copy pasting the main display then adjusting position and coloring though, which feels a bit messy.

I cant figure out an actual cleaner method to do so. The best thing I can think of is checking if the inspector is ctb then looping & adding, but I feel it's possible for it to be better than that.

2023-02-14 22:49 UTC, srb2thepast commented on PerformanceCalculatorGUI/Screens/ObjectInspection/DebugValueList.cs
> +                    flowContainer.AddText($"   {ValuePair.Key}:\n", t =>
`Margin` seems to apply to each word that gets added rather than only the first. It seems the only other way to do so without whitespace would be to create two Drawables (one `SpriteText` for the text and one `TextFlowContainer` with margin) for every group that's added, but I'm not sure if that's a good direction to go in. Do you have any suggestions?

2023-02-14 22:56 UTC, srb2thepast commented
Alright, nearly all the suggestions from each review have been implemented. The ones unresolved are those in which clarification is awaited. I believe it's ready for another review.

2023-02-18 14:45 UTC, stanriders requested changes
Still think it can be done way simplier by passing current difficulty hitobject straight into the `ObjectDifficultyValuesContainer`. There are also still a lot of formatting and naming issues

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/CatchObjectInspectorRuleset.cs
> +        private ObjectDifficultyValuesContainer debugValueList { get; set; }
Rename

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/CatchObjectInspectorRuleset.cs
> +        private Bindable<DifficultyHitObject> focusedDiffHitBind;
Please don't shorten the variable names
`currentDifficultyHitObjectBindable` reads way better

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/CatchObjectInspectorRuleset.cs
> +            focusedDiffHitBind.Value = null;
````csharp
focusedDiffHitBind.Value = difficultyHitObjects.LastOrDefault(h => h.StartTime <= Clock.CurrentTime)
````
Storing previous hitobject isn't really necessary as bindable will only update when the value changes

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/CatchObjectInspectorRuleset.cs
>                  {
Remove empty functions

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +            AddRange(new Drawable[] {
Formatting

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +                                new Box { Colour = Colour4.Gray, RelativeSizeAxes = Axes.Both, Y = 2},
Pretty sure this can be done way easier in `CatchObjectInspectorRuleset` without using lots of magic values

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/CatchObjectInspectorRuleset.cs
> +        public void UpdateDebugList(ObjectDifficultyValuesContainer valueList, DifficultyHitObject curDiffHit)
Naming

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/CatchObjectInspectorRuleset.cs
> +            Dictionary<string, Dictionary<string, object>> infoDict = valueList.InfoDictionary.Value;
I feel like its still all over the place - I expected hitobject bindable to be passed into the `ObjectDifficultyValuesContainer` and processed there

2023-02-18 14:45 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectDifficultyValuesContainer.cs
> +            focusedDiffHit.BindTo(diffHitBind);
Make `focusedDiffHit` a public get-only property and bind from the outside

2023-02-18 20:37 UTC, stanriders commented
Hope you don't mind, but I've refactored and slightly restyled the PR. Please take a look at what I roughly meant by using a `Bindable` for passing a hitobject into the values container. I'm still not completely satisfied with how it works (ideally I'd get rid of passing everything through rulesets, but that's a task for another day), but it's way more manageable now.

![image](https://user-images.githubusercontent.com/8269193/219896094-57c3a69c-b2ae-42ca-bbee-49c1201d6914.png)

2023-02-19 15:05 UTC, stanriders commented
> In osu!catch, if the Normalized Position's value is wide enough, it can intersect with the Normalized Position text:

I've changed the font so it fits now 

> While scrolling, the difficulty value text can slightly pass through the top of the ObjectDifficultyValuesContainer.

I'm not sure how to fix that since it looks like a masking issue. I'll leave it to the lazer devs to fix/explain if they want to since its a pretty much nonexisting bug from the usability standpoint

2023-02-22 13:17 UTC, stanriders approved these changes

2023-02-24 04:49 UTC, peppy commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectDifficultyValuesContainer.cs
> +            switch (ruleset.Value.ShortName)
Could use

```csharp
switch (hitObject)
{
    case OsuDifficultyObject osuObject:
        drawOsuValues(osuObject);
        break;
// etc.
}
```

to avoid string matching.

2023-02-24 04:49 UTC, peppy commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +            if (e.Key == Key.Q)
Any reason to use non-standard keys? Use arrow keys to match the editor?

2023-02-25 16:58 UTC, srb2thepast commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +            if (e.Key == Key.Q)
No, arrow keys fit much more.

2023-02-25 17:20 UTC, peppy commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +                    seekTo -= 100;
FWIW you're implementing this:

https://github.com/ppy/osu/blob/7bc8908ca9c026fed1d831eb6e58df7624a8d614/osu.Game/Screens/Edit/EditorClock.cs#L87-L92

but in a bit of a weird way. since the keys are skipping to the next object, isn't this potentially going to skip back more than one object at a time? I'm not sure this is a correct approach.

2023-02-25 17:20 UTC, peppy commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +                    seekTo -= 100;
And please, if changing behaviour like this, please please please don't bundle it in a commit which says nothing about the change being made...

2023-02-25 17:40 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +                    seekTo -= 100;
I don't think it matters that much to seek accurately when the clock is running anyway, the only real use case for it I can come up with is going back like a couple of seconds using arrows instead of the timeline. Since you can only see one object's difficulty values at a time, having clock running makes the inspection pretty much unusable anyway

Sure, I'll add minor stuff to the commit messages too

2023-02-25 17:45 UTC, peppy approved these changes

2023-02-25 17:45 UTC, merged

2023-02-25 17:45 UTC, peppy commented on PerformanceCalculatorGUI/Screens/ObjectInspection/ObjectInspector.cs
> +            if (e.Key == Key.Q)
Please fix that in a follow-up PR. This one already has too much going on.