Add buttons that can open the file path directly.
ppy/osu-tools pull request #202
Opened 2024-03-14 04:19 UTC by CloudeaSoft

[https://github.com/ppy/osu-tools/issues/201](url)
The codes for the issue#201.

2024-03-14 07:01 UTC, stanriders requested changes

2024-03-14 07:01 UTC, stanriders commented on PerformanceCalculatorGUI/Components/SettingsPopover.cs
> +            Process.Start("explorer.exe", folderPath);
This wont work on platforms other than windows

2024-03-14 07:01 UTC, stanriders commented on PerformanceCalculatorGUI/Components/SettingsPopover.cs
> +                                            Action = openPathDirectory
I'm not sure how useful this even is - you can always just copypaste the path from the text field into the file manager address bar

2024-03-14 07:36 UTC, CloudeaSoft commented on PerformanceCalculatorGUI/Components/SettingsPopover.cs
> +            Process.Start("explorer.exe", folderPath);
Ok, i'll try to make it more simply for other platforms.

2024-03-14 07:39 UTC, CloudeaSoft commented on PerformanceCalculatorGUI/Components/SettingsPopover.cs
> +                                            Action = openPathDirectory
I thought osu! have buttons for root path/skin path/beatmap path(in editor), so i tried to add this button.

2024-03-14 07:58 UTC, smoogipoo requested changes

2024-03-14 07:58 UTC, smoogipoo commented on PerformanceCalculatorGUI/Components/SettingsPopover.cs
> +        }
The correct solution here is to use `Storage.PresentExternally()`. You should be able to directly inject `GameHost` as a dependency here. Something like the following might be enough:
```
host.GetStorage(path).PresentExternally();
```

2024-03-14 08:00 UTC, CloudeaSoft commented on PerformanceCalculatorGUI/Components/SettingsPopover.cs
> +        }
Thx for the advice! :)

2024-03-18 15:48 UTC, Ireadosucode commented on PerformanceCalculatorGUI/Components/SettingsPopover.cs
> +                                            Action = openPathDirectory
it's quality of life for sure- not to mention a lot of people don't know how to do that

2024-03-18 15:48 UTC, Ireadosucode commented on PerformanceCalculatorGUI/Components/SettingsPopover.cs
> +                                            Action = openPathDirectory
somehow..

2024-04-04 13:06 UTC, closed without merging