Change ObjectInspector to work via object selection
ppy/osu-tools pull request #208
Opened 2024-07-18 23:03 UTC by Givikap120

This change is **unfinished**. I'm PRing this to have more clear guidance of what I need to do.

Summary:
I have abstract pooling logic implemented by classes in the folder General. But those classes are only used by STD selection, as Catch and Taiko don't have public tools that can allow those classes to be used here. 
The selection logic is implemented in the class `SelectableHitObject`.
Catch and Taiko don't have implemented selection logic yet, only outline display.

Questions:
- Do I need to merge STD classes with abstract base as the abstractions isn't used anywhere else?
- How can I add selection logic to the `CatchSelectableDrawableObject` and `TaikoSelectableDrawableObject` without copying? Or I just need to copy it and that's all?
- Do I need to implement selectable spinner (and other objects without respective difficulty hit objects)?
- Selectable object creation can be done with using DrawablePool. But seems to work fine without it. Do I need to do it?

2024-07-19 03:14 UTC, stanriders commented
> * Do I need to merge STD classes with abstract base as the abstractions isn't used anywhere else?

Yes
> * How can I add selection logic to the `CatchSelectableDrawableObject` and `TaikoSelectableDrawableObject` without copying? Or I just need to copy it and that's all?

Copying is fine if can't be moved out easily
> * Do I need to implement selectable spinner (and other objects without respective difficulty hit objects)?

No
> * Selectable object creation can be done with using DrawablePool. But seems to work fine without it. Do I need to do it?

Try running very high object count maps and see how big of a performance hit you get. If it's negligible and your system is more or less average it should be fine I think

2024-07-19 20:59 UTC, Givikap120 commented
Known issues:
- Taiko selected objects are appearing as "deselected" when scrolling back earlier than half of the playfield
- Taiko selected objects are appearing as "deselected" after time it should be hit (even tho Drawable looks like it's still goes to the left)
- Catch selected objects that were creating from nested fruits (slider ends) are fading-in for some reason

First two are most likely because of how pooling in Taiko works
Third is because of some internal catch playfield behavior (didn't found where the fade is applied)

Don't know how to fix the issues, and they're not critical, so waiting on commentary of this situation

2024-08-01 07:59 UTC, stanriders requested changes

2024-08-01 07:59 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/Catch/CatchObjectInspectorRuleset.cs
> +                foreach (var selectable in selectables)
Shouldn't the selectable itself process the input and playfield (or inspection panel) listen to select events? I feel like iterating over every object might get expensive very fast

2024-08-02 10:51 UTC, Givikap120 commented on PerformanceCalculatorGUI/Screens/ObjectInspection/Catch/CatchObjectInspectorRuleset.cs
> +                foreach (var selectable in selectables)
Fixed

2024-12-06 10:00 UTC, smoogipoo commented on PerformanceCalculatorGUI/Screens/ObjectInspection/Catch/CatchObjectInspectorRuleset.cs
> +#nullable enable
In general we don't `#nullable enable` in new files.

2024-12-06 10:01 UTC, stanriders commented on PerformanceCalculatorGUI/Screens/ObjectInspection/Catch/CatchObjectInspectorRuleset.cs
> +#nullable enable
I'm planning to go over the whole project and enabling nullables everywhere after I'm done refactoring this pr

2025-06-22 23:29 UTC, closed without merging