Added Accuracy, Misscount, and Max Combo columns
ppy/osu-tools pull request #83
Opened 2021-05-26 20:55 UTC by Finadoggie

more nice qol, this time with some help from StanR

2021-05-26 21:00 UTC, Finadoggie commented
shit, that's not supposed to happen

2021-05-26 21:05 UTC, stanriders requested changes

2021-05-26 21:05 UTC, stanriders commented on PerformanceCalculator/Profile/ProfileCommand.cs
> +                var perfCalc = ruleset.CreatePerformanceCalculator(working, score.ScoreInfo);
You're creating a second `PerformanceCalculator` right after the first one (line 87), don't think that's needed

2021-05-26 21:05 UTC, stanriders commented on PerformanceCalculator/Profile/ProfileCommand.cs
> +                try
`try-catch` block here isn't needed

2021-05-26 21:05 UTC, stanriders commented on PerformanceCalculator/Profile/ProfileCommand.cs
> +                    pp = perfCalc.Calculate(categories);
This value isn't being used (I think you mean to put it on line 110)

2021-05-26 22:18 UTC, Finadoggie commented
```
dotnet : An error occurred when executing task 'InspectCode'.
At C:\projects\osu-tools\InspectCode.ps1:26 char:1
+ dotnet cake ./build/InspectCode.cake $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr... 'InspectCode'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error: 
One or more errors occurred. (inspectcode failed with return code 5)
	inspectcode failed with return code 5
Command executed with exception: One or more errors occurred. (inspectcode failed with return code 5)
	inspectcode failed with return code 5

```
I'm not sure what this error means and/or how to fix it, and the tools work fine when I'm running the commands so idk why it's even firing errors

2021-05-26 22:31 UTC, bdach commented
Please see the "messages" tab in the appveyor CI result. There are some static analysis inspections therein to fix.

2021-05-26 23:01 UTC, Finadoggie commented
Bdach and StanR, you guys are lifesavers!

2021-05-27 00:28 UTC, tybug commented
For future reference, "update profilecommand.cs" isn't a very useful commit message. Better to say something like "fix inspection errors", if in fact that's what that commit is doing.

2021-05-27 00:38 UTC, Finadoggie commented
aight, that was just the name it gave all the commits that I didn't name, and I thought it would be assumed that every unnamed update was just a "fix the broken" commit

2021-05-27 03:01 UTC, smoogipoo requested changes

2021-05-31 10:42 UTC, smoogipoo approved these changes
lgtm

2021-05-31 10:42 UTC, merged